config/routes.rb
Rails.application.routes.draw do
  get 'flights/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root 'flights#index'
  resources :flights, only: [:index]
  resources :bookings, only: [:new, :create, :show]

end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departing_flights, class_name: "Flight", foreign_key: "departure_airport_id"
    has_many :arriving_flights, class_name: "Flight", foreign_key: "arrival_airport_id"

    validates :code, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers, dependent: :destroy
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :departure_airport, class_name: "Airport"
    belongs_to :arrival_airport, class_name: "Airport"

    def self.search(departure_airport_id, arrival_airport_id, flight_date, passenger_count)
        flights = Flight.all
    
        if departure_airport_id.present?
          flights = flights.where(departure_airport_id: departure_airport_id)
        end
    
        flights
    end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def new
        @booking = Booking.new(flight_id: params[:flight_id])
        params[:passenger_count].to_i.times { @booking.passengers.build }
    end

    def create
        @flight = Flight.find(params[:booking][:flight_id])
        @booking = Booking.build(booking_params)
        if @booking.save
          redirect_to @booking
        else
          render :new
        end
    end

    def show
        @booking = Booking.find(params[:id])
        @flight = Flight.find(@booking.flight_id)
    end      
      
    private
      
    def booking_params
        params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    if params[:departure_airport_id].present? && params[:arrival_airport_id].present? && params[:flight_date].present? && params[:passenger_count].present?
      @flights = Flight.search(params[:departure_airport_id], params[:arrival_airport_id], params[:flight_date], params[:passenger_count])
    else 
      @flights = []
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<%= form_with(model: @booking, url: bookings_path) do |form| %>
    <%= form.hidden_field :flight_id %>
    <% @booking.passengers.each do |passenger| %>
      <%= form.fields_for :passengers, passenger do |passenger_fields| %>
        <br><br>
        <div>
          <%= passenger_fields.label :name %>
          <%= passenger_fields.text_field :name %>
        </div>
        <div>
          <%= passenger_fields.label :email %>
          <%= passenger_fields.email_field :email %>
        </div>
      <% end %>
    <% end %>
    <%= form.submit "Book Now" %>
<% end %>
  

app/views/bookings/show.html.erb
<h1>Booking Details</h1>

<p><strong>Flight:</strong> <%= @flight.departure_airport.code %> to <%= @flight.arrival_airport.code %> on <%= @flight.start_datetime.strftime("%B %d, %Y") %> at <%= @flight.start_datetime.strftime("%I:%M %p") %></p>

<h2>Passenger Information</h2>
<ul>
  <% @booking.passengers.each do |passenger| %>
    <li>
      <strong>Name:</strong> <%= passenger.name %><br>
      <strong>Email:</strong> <%= passenger.email %>
    </li>
  <% end %>
</ul>

<%= link_to "Back", bookings_path %>

app/views/flights/index.html.erb
<%= form_tag flights_path, method: :get do %>
    <%= select_tag :departure_airport_id, options_for_select(Airport.pluck(:code, :id)) %>
    <%= select_tag :arrival_airport_id, options_for_select(Airport.pluck(:code, :id)) %>
    <%= select_tag :passenger_count, options_for_select([1, 2, 3, 4]) %>
    <%= select_tag :flight_date, options_for_select(Flight.distinct.pluck(:start_datetime).map { |date| [date.strftime("%B %d, %Y"), date] }) %>
    <%= submit_tag "Search" %>
<% end %>
<br><br>
<% if @flights.present? %>
  <%= form_tag new_booking_path, method: :get do %>
      <%= hidden_field_tag :passenger_count, params[:passenger_count] %>
      <% @flights.each do |flight| %>
        <%= radio_button_tag 'flight_id', flight.id %>
        <%= flight.departure_airport.code %> to <%= flight.arrival_airport.code %> on <%= flight.start_datetime.strftime("%B %d, %Y") %> at <%= flight.start_datetime.strftime("%I:%M %p") %>
        <br>
      <% end %>
      <%= submit_tag "Select Flight" %>
  <% end %>
<% end %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>